# Generated by Django 3.2.13 on 2022-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsapi', '0003_auto_20220607_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.CharField(max_length=255),
        ),
    ]
